### ISSUE TITLE
[BUG] make install failed ,"make: *** No rule to make target 'bin/controller-gen', needed by 'manifests'.  Stop."

### ISSUE THREAD

**Issue by wangzhilin90** [Triton-io/Triton#15]
**What happened**: 
1.make install failed
make: *** No rule to make target 'bin/controller-gen', needed by 'manifests'.  Stop.

**What you expected to happen**:
make install success

**How to reproduce it (as minimally and precisely as possible)**:
1.git clone https://github.com/triton-io/triton.git
2.helm install kruise https://github.com/openkruise/kruise/releases/download/v0.10.0/kruise-chart.tgz
3.make install 

**Anything else we need to know?**:

**Environment**:

- triton version:
0.1.0

- Kubernetes version (use `kubectl version`): kubernetes v1.18.8
- OS (e.g: `cat /etc/os-release`): centos7.6
- Kernel (e.g. `uname -a`): 
- Linux master1 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
****
- Install tools: 
- Others:

**Comment by hantmac** [comment]
@wangzhilin90 You should `make controller-gen` first

**Comment by wangzhilin90** [comment]
> @wangzhilin90 You should `make controller-gen` first

wechat code has expired，can you invite me to triton group

**Comment by hantmac** [comment]
> > @wangzhilin90 You should `make controller-gen` first
> 
> wechat code has expired，can you invite me to triton group

Of course, I have update the wechat code, thanks for your comment.

**Comment by wangzhilin90** [comment]
![image](https://user-images.githubusercontent.com/26026314/136533422-a5a4dd5f-f9fd-4df5-85aa-3ffc1a37df84.png)

root@master1:/home/deployflow# kubectl describe deployflows.apps.triton.io 12122-sample-10010-df
Name:         12122-sample-10010-df
Namespace:    default
Labels:       app=12122
              app.kubernetes.io/instance=12122-sample-10010
              app.kubernetes.io/name=deploy-demo-hello
              group=10010
              managed-by=triton-io
Annotations:  API Version:  apps.triton.io/v1alpha1
Kind:         DeployFlow
Metadata:
  Creation Timestamp:  2021-10-08T09:25:59Z
  Generation:          1
  Managed Fields:
    API Version:  apps.triton.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:app:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/name:
          f:group:
          f:managed-by:
      f:spec:
        .:
        f:action:
        f:application:
          .:
          f:appID:
          f:appName:
          f:groupID:
          f:instanceName:
          f:replicas:
          f:selector:
            .:
            f:matchLabels:
              .:
              f:app:
              f:app.kubernetes.io/instance:
              f:app.kubernetes.io/name:
              f:group:
              f:managed-by:
          f:template:
            .:
            f:metadata:
            f:spec:
              .:
              f:containers:
        f:updateStrategy:
          .:
          f:batchIntervalSeconds:
          f:batchSize:
          f:batches:
          f:canary:
          f:mode:
    Manager:         kubectl
    Operation:       Update
    Time:            2021-10-08T09:25:59Z
  Resource Version:  5649216
  Self Link:         /apis/apps.triton.io/v1alpha1/namespaces/default/deployflows/12122-sample-10010-df
  UID:               54826c28-1bf2-44af-b468-320822bf6c31
Spec:
  Action:  create
  Application:
    App ID:         12122
    App Name:       deploy-demo-hello
    Group ID:       10010
    Instance Name:  12122-sample-10010
    Replicas:       3
    Selector:
      Match Labels:
        App:                         12122
        app.kubernetes.io/instance:  12122-sample-10010
        app.kubernetes.io/name:      deploy-demo-hello
        Group:                       10010
        Managed - By:                triton-io
    Template:
      Metadata:
      Spec:
        Containers:
          Image:  nginx:latest
          Name:   12122-sample-10010-container
          Ports:
            Container Port:  80
            Protocol:        TCP
          Resources:
  Update Strategy:
    Batch Interval Seconds:  10
    Batch Size:              1
    Batches:                 1
    Canary:                  1
    Mode:                    auto
Events:                      <none>


another question happend, when i apply nginx-deployflow.yaml,the status is null
