### ISSUE TITLE
[BUG]  make run  failed,提示“recipe for target 'run' failed”

### ISSUE THREAD

**Issue by wangzhilin90** [Triton-io/Triton#16]
**What happened**:
1.deployflow 副本数不正常，没有达到期望值，报错如下图：
![image](https://user-images.githubusercontent.com/26026314/136551107-cb89a77d-1c18-4e17-beca-35bd06baed44.png)
因为没有执行make run,
2.执行make run 后，报错“recipe for target 'run' failed”
![image](https://user-images.githubusercontent.com/26026314/136551655-f9a55820-9dd1-44f6-b9ec-3a8d1395166a.png)

3.查找/var/log/localhost日志报错如下
time="2021-10-08T17:43:39.227584+08:00" level=info msg="NumCPU: 4, GOMAXPROCS: 4\n" func=Infof file="log/log.go:117"
time="2021-10-08T17:43:39.229314+08:00" level=error msg="failed to get filed indexer" func=newReconciler file="deployflow/deployflow_controller.go:91" controller=DeployFlow
![image](https://user-images.githubusercontent.com/26026314/136551957-46e484f1-1998-42ff-9b63-c3d6aa37c853.png)

**What you expected to happen**:
deployflow 副本数正常

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- triton version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hantmac** [comment]
shoule `kubectl create ns triton-system` before `make run` .
